# Generated by Django 5.2.12 on 2026-04-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_tag_and_task_tag_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
