# Generated by Django 5.2.12 on 2026-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
